# Loads default set of integrations. Do not remove.
default_config:

# Frontend & thèmes
frontend:
  themes: !include_dir_merge_named themes

# Configuration Home Assistant
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        192.168.1.136: c12d9a92e4ab44b99a3f8a0cf93719a1
      allow_bypass_login: true

# Automations & scripts
automation: !include automations.yaml
script: !include scripts.yaml

# Covers
cover: !include_dir_merge_list covers

# Template sensors
template: !include templates/climate_sensors.yaml

input_select: !include input_select.yaml
groups: !include groups.yaml

# Groupe spécifique à l'iPad
group:
  ipad_dashboard:
    name: iPad
    entities:
      - sensor.time
      - weather.forecast_maison
      - light.salondejardin
      - climate.sejour
      - sensor.backup_backup_manager_state

lovelace:
  dashboards:
    lovelace-ios:
      mode: yaml
      title: iOS Dashboard Premium
      icon: mdi:tablet
      show_in_sidebar: true
      filename: dashboards/ios_dashboard/dashboard.yaml
